name: djlint

on:
  push:
    paths:
      - 'basicswap/templates/**'
      - '**'
  pull_request:
    paths:
      - 'basicswap/templates/**'
jobs:
  djlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install djlint
      run: |
        pip install djlint
    - name: Run djlint
      run: |
        djlint basicswap/templates || true
